apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invest-channel-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/FISA-BOCE/WON-GitOps.git
    targetRevision: develop
    path: apps/invest-channel-server
    helm:
      valueFiles:
        - ../../environments/securities/dev/invest-channel-server-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: securities-dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
