replicaCount: 1

image:
  repository: 099622554242.dkr.ecr.ap-northeast-2.amazonaws.com/won-card-channel-server
  tag: main-646a73a

service:
  targetPort: 8081

spring:
  profile: prod

env:
  - name: SERVER_PORT
    value: "8081"

config:
  enabled: true
  data:
    MYSQL_PORT: "3306"
    MYSQL_DATABASE: won_card_channel_db
    AWS_REGION: ap-northeast-2

secret:
  enabled: true
  name: card-channel-secret

probes:
  enabled: true
  path: /actuator/health
  initialDelaySeconds: 90
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
