replicaCount: 1

image:
  repository: nginx
  tag: "1.27-alpine"

service:
  targetPort: 80

spring:
  profile: dev

env: []

config:
  enabled: true
  data:
    LOG_LEVEL: INFO

probes:
  enabled: true
  path: /

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
